"""Add user location and notification fields

Revision ID: 26b3b232e047
Revises: 5f66bb321e7d
Create Date: 2025-09-20 20:20:52.603203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26b3b232e047'
down_revision = '5f66bb321e7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_alert', sa.Boolean(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('push_token', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('push_token')

    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_column('is_alert')

    # ### end Alembic commands ###
