"""Add alert system fields

Revision ID: 5f66bb321e7d
Revises: 0391715ef3c0
Create Date: 2025-09-20 16:18:50.701482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f66bb321e7d'
down_revision = '0391715ef3c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('alert_radius', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('alert_sent', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('alert_sent_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('home_latitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('home_longitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('alert_preferences', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('alert_preferences')
        batch_op.drop_column('home_longitude')
        batch_op.drop_column('home_latitude')

    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.drop_column('alert_sent_at')
        batch_op.drop_column('alert_sent')
        batch_op.drop_column('alert_radius')

    # ### end Alembic commands ###
