"""Add status and priority to report

Revision ID: 8b8777ac801a
Revises: 26b3b232e047
Create Date: 2026-01-23 20:11:41.329486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b8777ac801a'
down_revision = '26b3b232e047'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('metro_simulation')
    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('priority', sa.String(length=20), nullable=True))

    with op.batch_alter_table('report_view', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.create_unique_constraint('unique_report_view', ['user_id', 'report_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report_view', schema=None) as batch_op:
        batch_op.drop_constraint('unique_report_view', type_='unique')
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.drop_column('priority')
        batch_op.drop_column('status')

    op.create_table('metro_simulation',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('city_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('created_by', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('metro_line_geojson', sa.TEXT(), nullable=True),
    sa.Column('stations_geojson', sa.TEXT(), nullable=True),
    sa.Column('assumptions', sa.TEXT(), nullable=True),
    sa.Column('traffic_reduction', sa.FLOAT(), nullable=True),
    sa.Column('aqi_improvement', sa.FLOAT(), nullable=True),
    sa.Column('affected_roads', sa.TEXT(), nullable=True),
    sa.Column('results_geojson', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
