"""Add assignment_id to Notification model

Revision ID: add_notification_assignment
Revises: add_rescue_completion_fields
Create Date: 2026-01-25 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_notification_assignment'
down_revision = 'add_rescue_completion_fields'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assignment_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_notification_assignment_id', 'volunteer_assignments', ['assignment_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_constraint('fk_notification_assignment_id', type_='foreignkey')
        batch_op.drop_column('assignment_id')

    # ### end Alembic commands ###
