"""Add Urban Resilience Index tables

Revision ID: ec15d6b69125
Revises: add_notification_assignment
Create Date: 2026-01-30 22:59:10.175311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec15d6b69125'
down_revision = 'add_notification_assignment'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create resilience_zones table
    op.create_table('resilience_zones',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('zone_identifier', sa.String(length=100), nullable=False),
        sa.Column('zone_type', sa.String(length=50), nullable=True),
        sa.Column('center_latitude', sa.Float(), nullable=False),
        sa.Column('center_longitude', sa.Float(), nullable=False),
        sa.Column('bounds_geojson', sa.Text(), nullable=True),
        sa.Column('display_name', sa.String(length=200), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('zone_identifier')
    )
    
    # Create resilience_scores table
    op.create_table('resilience_scores',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('zone_id', sa.Integer(), nullable=False),
        sa.Column('score', sa.Float(), nullable=False),
        sa.Column('trend', sa.String(length=20), nullable=True),
        sa.Column('calculation_period', sa.String(length=20), nullable=True),
        sa.Column('calculated_at', sa.DateTime(), nullable=True),
        sa.Column('metrics_json', sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(['zone_id'], ['resilience_zones.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=60),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.create_unique_constraint('uq_user_whatsapp_number', ['whatsapp_number'])

    with op.batch_alter_table('volunteer_assignments', schema=None) as batch_op:
        batch_op.alter_column('points_earned',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'0'"))

    with op.batch_alter_table('volunteers', schema=None) as batch_op:
        batch_op.alter_column('points',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('total_rescues',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'0'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop resilience tables
    op.drop_table('resilience_scores')
    op.drop_table('resilience_zones')
    
    with op.batch_alter_table('volunteers', schema=None) as batch_op:
        batch_op.alter_column('total_rescues',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('points',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'0'"))

    with op.batch_alter_table('volunteer_assignments', schema=None) as batch_op:
        batch_op.alter_column('points_earned',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'0'"))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_whatsapp_number', type_='unique')
        batch_op.alter_column('role',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('password',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=60),
               existing_nullable=False)
        batch_op.alter_column('username',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###
